# This Makefile is generated by omake: https://github.com/ouonline/omake.git

CXX := g++

ifeq ($(debug), y)
	CXXFLAGS += -g
else
	CXXFLAGS += -O2 -DNDEBUG
endif

AR := ar

TARGET := libnetkit_shared.so libnetkit_static.a

.PHONY: all clean distclean

all: $(TARGET)

.PHONY: omake_phony_0
omake_phony_0:
	$(MAKE) debug=$(debug) libthreadkit_static.a -C ../threadkit

.PHONY: omake_phony_1
omake_phony_1:
	$(MAKE) debug=$(debug) liblogger_static.a -C ../logger

omake_dep_0_INCLUDE := -I..

omake_dep_0.connection.cpp.o: connection.cpp
	$(CXX) $(CXXFLAGS) -Wall -Werror -Wextra -fPIC $(omake_dep_0_INCLUDE) -c $< -o $@

omake_dep_0.event_manager.cpp.o: event_manager.cpp
	$(CXX) $(CXXFLAGS) -Wall -Werror -Wextra -fPIC $(omake_dep_0_INCLUDE) -c $< -o $@

omake_dep_0.internal_client.cpp.o: internal_client.cpp
	$(CXX) $(CXXFLAGS) -Wall -Werror -Wextra -fPIC $(omake_dep_0_INCLUDE) -c $< -o $@

omake_dep_0.internal_server.cpp.o: internal_server.cpp
	$(CXX) $(CXXFLAGS) -Wall -Werror -Wextra -fPIC $(omake_dep_0_INCLUDE) -c $< -o $@

omake_dep_0.processor_manager.cpp.o: processor_manager.cpp
	$(CXX) $(CXXFLAGS) -Wall -Werror -Wextra -fPIC $(omake_dep_0_INCLUDE) -c $< -o $@

netkit_shared_OBJS := omake_dep_0.internal_server.cpp.o omake_dep_0.internal_client.cpp.o omake_dep_0.processor_manager.cpp.o omake_dep_0.event_manager.cpp.o omake_dep_0.connection.cpp.o

netkit_shared_LIBS := ../threadkit/libthreadkit_static.a ../logger/liblogger_static.a ../utils/libutils_static.a -lpthread

libnetkit_shared.so: $(netkit_shared_OBJS) | omake_phony_1 omake_phony_0
	$(CXX) $(CXXFLAGS) -Wall -Werror -Wextra -fPIC -shared -o $@ $^ $(netkit_shared_LIBS)

netkit_static_OBJS := omake_dep_0.internal_server.cpp.o omake_dep_0.internal_client.cpp.o omake_dep_0.processor_manager.cpp.o omake_dep_0.event_manager.cpp.o omake_dep_0.connection.cpp.o

libnetkit_static.a: $(netkit_static_OBJS) | omake_phony_1 omake_phony_0
	$(AR) rc $@ $^

clean:
	rm -f $(TARGET) $(netkit_shared_OBJS) $(netkit_static_OBJS)

distclean:
	$(MAKE) clean
	$(MAKE) distclean -C ../logger
	$(MAKE) distclean -C ../threadkit
